<?php

declare(strict_types=1);

use Symfony\Component\Config\Definition\Configurator\DefinitionConfigurator;

return static function (DefinitionConfigurator $definition): void {
    $definition->rootNode()
        ->children()
            ->arrayNode('algorithms')
                ->info('Accepted JWS signature algorithms for the device-bound key.')
                ->scalarPrototype()->end()
                ->defaultValue(['ES256', 'RS256'])
            ->end()
            ->scalarNode('binding_repository')
                ->info('Service id of the persistent SessionBindingRepository implementation. Defaults to in-memory.')
                ->defaultNull()
            ->end()
            ->scalarNode('registration')
                ->info('Path of the DBSC registration endpoint (StartSession).')
                ->defaultValue('/dbsc/register')
            ->end()
            ->scalarNode('refresh')
                ->info('Path of the DBSC refresh endpoint.')
                ->defaultValue('/dbsc/refresh')
            ->end()
            ->integerNode('challenge_ttl')
                ->info('Lifetime of a single-use challenge, in seconds.')
                ->defaultValue(300)
            ->end()
            ->arrayNode('cookie')
                ->addDefaultsIfNotSet()
                ->children()
                    ->scalarNode('name')
                        ->info('Name of the short-lived device-bound cookie.')
                        ->defaultValue('__Host-dbsc_session')
                    ->end()
                    ->integerNode('lifetime')
                        ->info('Lifetime of the bound cookie, in seconds.')
                        ->defaultValue(600)
                    ->end()
                    ->scalarNode('path')->defaultValue('/')->end()
                    ->scalarNode('domain')->defaultNull()->end()
                    ->booleanNode('secure')->defaultTrue()->end()
                    ->booleanNode('http_only')->defaultTrue()->end()
                    ->enumNode('same_site')
                        ->values(['lax', 'strict', 'none'])
                        ->defaultValue('lax')
                    ->end()
                ->end()
            ->end()
        ->end()
    ;
};
